services:
  url:
    certificate-service: http://localhost:50000

server:
  port: 50200

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/shallwecode
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: choi0829
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect


spring:
  datasource:
    url: jdbc:h2:mem:shallwecode
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace

