#spring:
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:swc-test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
